security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:        [ROLE_USER]
        ROLE_REPRESENTANT_TERRITORIAL:        [ROLE_USER]    
        ROLE_MANAGER_AGENCE:        [ROLE_USER]    
        ROLE_ADMIN:       [ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_MANAGER_AGENCE, ROLE_REPRESENTANT_TERRITORIAL]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # login area for backoffice users
        backoffice:
            context: primary_auth
            pattern:            ^/admin
            form_login:
                provider:       fos_userbundle
                login_path:     grdf_back_office_security_login
                use_forward:    true
                use_referer:    true
                check_path:     grdf_back_office_security_check
                #failure_path:   null
                default_target_path: grdf_backofficebundle_home
            logout:
                path: grdf_back_office_security_logout
                target: grdf_back_office_security_login
            anonymous:    true

        # defaut login area for standard users
        main:
            context: primary_auth
            pattern:            ^/
            form_login:
                provider:       fos_userbundle
                login_path:     fos_user_security_login
                use_forward:    true
                use_referer:    true
                check_path:     fos_user_security_check
                #failure_path:   null
                default_target_path: fos_user_profile_show
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
            anonymous:    true

    access_control:
        # back-office

        - { path: ^/admin/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/private-space, roles: ROLE_USER }
        # front-office
        - { path: ^/inscription, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mot-de-passe-oublie/reinitialisation, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mot-de-passe-oublie, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mail, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mail/sendMail, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/deconnexion$, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/, role: ROLE_USER  }